include ./theme.conf
map ctrl+shift+enter new_os_window_with_cwd

font_family FiraCode Nerd Font Mono
font_size 11.0
cursor_shape beam
scrollback_lines 2000
sync_to_monitor yes
enable_audio_bell no 

background_opacity 1
